name: "Deploy site"

on:
  push:
    branches: ['master']

permissions: {}

jobs:
  deploy:
    name: Deploy lektor website
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '10'
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick
      - name: Verify ImageMagick Installation
        run: convert --version
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install "Flask==1.1.4"
          pip install Lektor
      - name: Install plugins
        run: lektor plugins reinstall
      - name: Build site
        run: lektor build
      - name: Deploy
        env:
          LEKTOR_DEPLOY_USERNAME: ${{ secrets.LEKTOR_DEPLOY_USERNAME }}
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.LEKTOR_DEPLOY_PASSWORD }}
        run: lektor deploy ghpages
